### ISSUE TITLE
style: UI 깨진 부분 수정

### ISSUE THREAD

**Issue by KJeeu** [RightMemeRightNow/right-meme-right-now#48]
## 📌Feature Description

> 전체적으로 UI 깨지는 부분 수정

## ✨ To-do

- [x] PC에서 버튼이 배경이미지 밖으로 벗어나는 버그 수정
- [x] Mobile에서 상단 여백 추가
- [x] Mobile에서 ProgressBar 길이 사이드 여백 추가
