### ISSUE TITLE
feat: 짤 이미지 저장

### ISSUE THREAD

**Issue by seonghun0828** [RightMemeRightNow/right-meme-right-now#5]
## 📌Feature Description

> 최종 추천 짤 페이지에서 저장 버튼을 클릭했을 때 내 컴퓨터에 이미지 파일(png 등)이 저장된다.

## ✨ To-do

- [x] 이미지 파일 저장하는 방법 리서치
  - a 태그 download 속성
- [x] 저장 버튼 UI 생성
- [x] 저장 버튼 클릭 시 이미지 파일 저장되도록 로직 추가
