### ISSUE TITLE
feat: 주소 공유할 때 미리보기 이미지 나오도록 설정

### ISSUE THREAD

**Issue by seonghun0828** [RightMemeRightNow/right-meme-right-now#8]
## 📌Feature Description

> 공유 버튼을 눌러 클립보드에 담은 주소를 다른 사람에게 공유할 때, 미리보기 이미지가 같이 나오도록 Next.js OGTag를 설정한다.
미리보기 이미지에서 결과 짤을 동적으로 보여줄 수도 있고, 우리 서비스의 대표 이미지만 공통되게(정적으로) 보여줄 수도 있다.
이 부분은 더 논의가 필요할 듯.

## ✨ To-do

- [x] OGTag에 대해 리서치
- [ ] 미리보기 이미지로 뭘 보여줄 지 토의
- [x] Next.js OGTag 설정
